"""
Core Models for the Creation Studio App.

This module provides models for managing:
- Content Creations and Generations
- Previews and Preview Items
"""

import uuid
from django.db import models

# Compatibility/Imports from other apps
from brand_dna_extractor.models import Brand, BrandDNA, generate_uuid
from platform_insights.models import Post, PlatformInsight


class Creation(models.Model):
    """
    Orchestrator of the content lifecycle.

    Manages the state of each generation request from webhook entry
    to completion. Records user intent, emotional impact, and target platforms.
    """

    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('in_progress', 'In Progress'),
        ('done', 'Done'),
        ('failed', 'Failed'),
        ('cancelled', 'Cancelled'),
    ]

    POST_TYPE_CHOICES = [
        ('post', 'Post'),
        ('image', 'Image'),
        ('copy', 'Copy'),
        ('carousel', 'Carousel'),
        ('reel', 'Reel'),
        ('video', 'Video'),
        ('story', 'Story'),
        ('infographic', 'Infographic'),
    ]

    uuid = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )

    brand = models.ForeignKey(
        'brand_dna_extractor.Brand',
        on_delete=models.CASCADE,
        related_name='creations',
        db_column='brand_uuid',
        null=True,
        blank=True,
    )

    # Creation details
    title = models.CharField(max_length=500)
    post_type = models.CharField(max_length=20, choices=POST_TYPE_CHOICES, default='post')
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')
    platforms = models.CharField(
        max_length=255,
        blank=True,
        help_text="Comma-separated platforms (e.g., instagram, tiktok)"
    )
    post_tone = models.CharField(max_length=50, blank=True, help_text="Desired emotional impact")

    # Timestamps
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'creations'
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['brand', 'status']),
            models.Index(fields=['status']),
            models.Index(fields=['created_at']),
        ]

    def __str__(self):
        return f"{self.title} ({self.uuid})"

    @property
    def platforms_list(self):
        """Return platforms as a list."""
        return [p.strip() for p in self.platforms.split(',') if p.strip()]


class Generation(models.Model):
    """
    Detailed ledger of AI iterations.

    Logs every individual attempt generated by vision models.
    Self-referencing architecture (parent_uuid) maintains genealogical history
    of how an asset evolved from first draft to final version.
    """

    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('processing', 'Processing'),
        ('done', 'Done'),
        ('failed', 'Failed'),
    ]

    TYPE_CHOICES = [
        ('image', 'Image'),
        ('video', 'Video'),
        ('copy', 'Copy'),
    ]

    uuid = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )

    creation = models.ForeignKey(
        Creation,
        on_delete=models.CASCADE,
        related_name='generations',
        db_column='creation_uuid'
    )

    # Self-referencing for version history
    parent = models.ForeignKey(
        'self',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='children',
        db_column='parent_uuid'
    )

    # Generation details
    type = models.CharField(max_length=50, choices=TYPE_CHOICES, default='image')
    prompt = models.TextField(blank=True, help_text="The optimized super-prompt used")
    content = models.TextField(blank=True, help_text="Generated content output")
    keywords = models.CharField(max_length=500, blank=True, help_text="Comma-separated keywords")
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')

    # Timestamps
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'generations'
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['creation', 'status']),
            models.Index(fields=['status']),
            models.Index(fields=['parent']),
        ]

    def __str__(self):
        return f"Generation {self.uuid}"


class Preview(models.Model):
    """
    A versioned preview composition of generations.

    Groups selected generations into a named preview version
    that can be reviewed before finalizing as a post.
    """

    uuid = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )

    # Preview details
    version_name = models.CharField(max_length=255, blank=True)
    internal_notes = models.TextField(blank=True)

    # Timestamps
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'preview'
        ordering = ['-created_at']

    def __str__(self):
        return f"Preview {self.version_name or self.uuid}"


class PreviewItem(models.Model):
    """
    Junction table linking Previews to Generations.

    Each item represents a specific generation used in a preview,
    with a position for ordering.
    """

    uuid = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )

    preview = models.ForeignKey(
        Preview,
        on_delete=models.CASCADE,
        related_name='items',
        db_column='preview_uuid'
    )

    generation = models.ForeignKey(
        Generation,
        on_delete=models.CASCADE,
        related_name='preview_items',
        db_column='generation_uuid'
    )

    position = models.IntegerField(default=0)

    class Meta:
        db_table = 'preview_items'
        ordering = ['position']
        indexes = [
            models.Index(fields=['preview', 'position']),
        ]

    def __str__(self):
        return f"PreviewItem {self.uuid} (pos={self.position})"