# Generated by Django 6.0.3 on 2026-03-16 16:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandDNA',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('primary_color', models.CharField(blank=True, help_text='Hex color code', max_length=7)),
                ('secondary_color', models.CharField(blank=True, help_text='Hex color code', max_length=7)),
                ('accent_color', models.CharField(blank=True, help_text='Hex color code', max_length=7)),
                ('complementary_color', models.CharField(blank=True, help_text='Hex color code', max_length=7)),
                ('font_body_family', models.CharField(blank=True, max_length=100)),
                ('font_headings_family', models.CharField(blank=True, max_length=100)),
                ('voice_tone', models.CharField(blank=True, max_length=255)),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated brand keywords')),
                ('description', models.TextField(blank=True, help_text='Brand description and positioning')),
                ('archetype', models.CharField(blank=True, help_text='Brand archetype', max_length=100)),
                ('target_audience', models.CharField(blank=True, help_text='Target audience description', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brand DNA',
                'verbose_name_plural': 'Brand DNA',
                'db_table': 'brand_dna',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, db_index=True, help_text='SIA User UUID (from OAuth/JWT) - who owns this brand', max_length=36, null=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('page_url', models.URLField(blank=True, max_length=500, validators=[django.core.validators.URLValidator()])),
                ('primary_color', models.CharField(blank=True, help_text='Hex color code', max_length=7)),
                ('logo_url', models.URLField(blank=True, max_length=500, validators=[django.core.validators.URLValidator()])),
                ('is_active', models.BooleanField(default=True)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dna', models.OneToOneField(blank=True, db_column='dna_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand', to='brand_dna_extractor.branddna')),
            ],
            options={
                'db_table': 'brands',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='brands_slug_6a4b1c_idx'), models.Index(fields=['is_active'], name='brands_is_acti_101dba_idx'), models.Index(fields=['industry'], name='brands_industr_2b91ff_idx')],
            },
        ),
    ]
