# Generated by Django 6.0.3 on 2026-03-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_dna_extractor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='tenant_id',
            field=models.CharField(blank=True, db_index=True, help_text='SIA Tenant UUID - which organization this brand belongs to', max_length=36, null=True),
        ),
    ]
