# Generated by Django 6.0.3 on 2026-03-16 19:36

import ai_chatbot.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand_dna_extractor', '0002_brand_tenant_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSuggestion',
            fields=[
                ('uuid', models.CharField(default=ai_chatbot.models.generate_chat_uuid, editable=False, max_length=17, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('onboarding', 'Onboarding'), ('strategy', 'Strategy'), ('content', 'Content Creation'), ('analytics', 'Analytics'), ('general', 'General'), ('brand', 'Brand Management')], default='general', max_length=20)),
                ('suggestion_text', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('required_conversation_type', models.CharField(blank=True, choices=[('general', 'General Chat'), ('onboarding', 'Business Onboarding'), ('strategy', 'Strategy Development'), ('content', 'Content Creation'), ('analytics', 'Performance Analytics'), ('competitor', 'Competitor Analysis'), ('brand_dna', 'Brand DNA Discussion'), ('creation', 'Creation Project')], help_text='Only show in specific conversation types', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chat_suggestions',
                'ordering': ['category', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('uuid', models.CharField(default=ai_chatbot.models.generate_chat_uuid, editable=False, max_length=17, primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, db_index=True, help_text='SIA User UUID who owns this conversation', max_length=36, null=True)),
                ('tenant_id', models.CharField(blank=True, db_index=True, help_text='SIA Tenant UUID - organization context', max_length=36, null=True)),
                ('title', models.CharField(default='New Conversation', max_length=255)),
                ('conversation_type', models.CharField(choices=[('general', 'General Chat'), ('onboarding', 'Business Onboarding'), ('strategy', 'Strategy Development'), ('content', 'Content Creation'), ('analytics', 'Performance Analytics'), ('competitor', 'Competitor Analysis'), ('brand_dna', 'Brand DNA Discussion'), ('creation', 'Creation Project')], default='general', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('completed', 'Completed')], default='active', max_length=20)),
                ('context_summary', models.TextField(blank=True, help_text='AI-generated summary of conversation context')),
                ('extracted_goals', models.JSONField(blank=True, default=dict, help_text='Business/marketing goals extracted from conversation')),
                ('brand_context', models.JSONField(blank=True, default=dict, help_text='Brand-specific context for this conversation')),
                ('session_metadata', models.JSONField(blank=True, default=dict, help_text='Additional session data (IP, user agent, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('brand', models.ForeignKey(blank=True, db_column='brand_uuid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='brand_dna_extractor.brand')),
            ],
            options={
                'db_table': 'chat_conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMemory',
            fields=[
                ('uuid', models.CharField(default=ai_chatbot.models.generate_chat_uuid, editable=False, max_length=17, primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('memory_type', models.CharField(choices=[('preference', 'User Preference'), ('business_fact', 'Business Fact'), ('brand_attribute', 'Brand Attribute'), ('goal', 'Business Goal'), ('constraint', 'Constraint/Limitation'), ('insight', 'Strategic Insight'), ('feedback', 'User Feedback')], max_length=20)),
                ('key', models.CharField(help_text='Semantic key for the memory', max_length=200)),
                ('value', models.TextField(help_text='Memory content')),
                ('value_structured', models.JSONField(blank=True, default=dict, help_text='Structured memory data')),
                ('confidence_score', models.FloatField(default=1.0, help_text='Confidence in this memory (0.0-1.0)')),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('access_count', models.PositiveIntegerField(default=0)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, db_column='brand_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_memories', to='brand_dna_extractor.brand')),
                ('source_conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_memories', to='ai_chatbot.chatconversation')),
            ],
            options={
                'db_table': 'chat_memories',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('uuid', models.CharField(default=ai_chatbot.models.generate_chat_uuid, editable=False, max_length=17, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System'), ('tool', 'Tool')], max_length=20)),
                ('message_type', models.CharField(choices=[('text', 'Text Message'), ('structured', 'Structured Data'), ('tool_call', 'Tool Call'), ('tool_result', 'Tool Result'), ('error', 'Error Message'), ('suggestion', 'Suggestion')], default='text', max_length=20)),
                ('content', models.TextField()),
                ('content_structured', models.JSONField(blank=True, default=dict, help_text='Structured content (cards, suggestions, etc.)')),
                ('tool_name', models.CharField(blank=True, help_text='Name of the tool if this is a tool call/result', max_length=100)),
                ('tool_input', models.JSONField(blank=True, default=dict, help_text='Input parameters for tool calls')),
                ('tool_output', models.JSONField(blank=True, default=dict, help_text='Output from tool execution')),
                ('agent_name', models.CharField(blank=True, help_text='Name of the agent that generated this message', max_length=50)),
                ('agent_reasoning', models.TextField(blank=True, help_text="Agent's reasoning process (for transparency)")),
                ('sources', models.JSONField(blank=True, default=list, help_text='References to data sources (database records, web URLs, etc.)')),
                ('tokens_used', models.PositiveIntegerField(blank=True, null=True)),
                ('processing_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(db_column='conversation_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_chatbot.chatconversation')),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['user_id', 'status'], name='chat_conver_user_id_138d55_idx'),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['brand', 'status'], name='chat_conver_brand_u_d7048f_idx'),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['conversation_type'], name='chat_conver_convers_405633_idx'),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['created_at'], name='chat_conver_created_62f1ed_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmemory',
            index=models.Index(fields=['user_id', 'memory_type'], name='chat_memori_user_id_4bad5d_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmemory',
            index=models.Index(fields=['brand', 'memory_type'], name='chat_memori_brand_u_9b956e_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmemory',
            index=models.Index(fields=['key'], name='chat_memori_key_012db3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatmemory',
            unique_together={('user_id', 'brand', 'key')},
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='chat_messag_convers_fe0bb3_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['role'], name='chat_messag_role_ddd811_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['agent_name'], name='chat_messag_agent_n_69de48_idx'),
        ),
    ]
