# Generated by Django 6.0.2 on 2026-03-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Combined embedding text: ai_description + use_cases + keywords + industry + mood + colors')),
                ('metadata', models.JSONField(default=dict, help_text='Full original template record from enriched_templates.json')),
                ('embedding_json', models.JSONField(blank=True, help_text='Embedding vector stored as JSON array (for SQLite compatibility)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'template_documents',
                'indexes': [models.Index(fields=['created_at'], name='template_do_created_7bbc01_idx')],
            },
        ),
    ]
