# Generated by Django 6.0.3 on 2026-03-16 16:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand_dna_extractor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preview',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_name', models.CharField(blank=True, max_length=255)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'preview',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Creation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('post_type', models.CharField(choices=[('post', 'Post'), ('image', 'Image'), ('copy', 'Copy'), ('carousel', 'Carousel'), ('reel', 'Reel'), ('video', 'Video'), ('story', 'Story'), ('infographic', 'Infographic')], default='post', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('done', 'Done'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('platforms', models.CharField(blank=True, help_text='Comma-separated platforms (e.g., instagram, tiktok)', max_length=255)),
                ('post_tone', models.CharField(blank=True, help_text='Desired emotional impact', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, db_column='brand_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creations', to='brand_dna_extractor.brand')),
            ],
            options={
                'db_table': 'creations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('copy', 'Copy')], default='image', max_length=50)),
                ('prompt', models.TextField(blank=True, help_text='The optimized super-prompt used')),
                ('content', models.TextField(blank=True, help_text='Generated content output')),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creation', models.ForeignKey(db_column='creation_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='creation_studio.creation')),
                ('parent', models.ForeignKey(blank=True, db_column='parent_uuid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='creation_studio.generation')),
            ],
            options={
                'db_table': 'generations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PreviewItem',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.IntegerField(default=0)),
                ('generation', models.ForeignKey(db_column='generation_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='preview_items', to='creation_studio.generation')),
                ('preview', models.ForeignKey(db_column='preview_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='creation_studio.preview')),
            ],
            options={
                'db_table': 'preview_items',
                'ordering': ['position'],
            },
        ),
        migrations.AddIndex(
            model_name='creation',
            index=models.Index(fields=['brand', 'status'], name='creations_brand_u_161e6a_idx'),
        ),
        migrations.AddIndex(
            model_name='creation',
            index=models.Index(fields=['status'], name='creations_status_484e73_idx'),
        ),
        migrations.AddIndex(
            model_name='creation',
            index=models.Index(fields=['created_at'], name='creations_created_6565e7_idx'),
        ),
        migrations.AddIndex(
            model_name='generation',
            index=models.Index(fields=['creation', 'status'], name='generations_creatio_6b2fbb_idx'),
        ),
        migrations.AddIndex(
            model_name='generation',
            index=models.Index(fields=['status'], name='generations_status_8c8b21_idx'),
        ),
        migrations.AddIndex(
            model_name='generation',
            index=models.Index(fields=['parent'], name='generations_parent__b8dc2b_idx'),
        ),
        migrations.AddIndex(
            model_name='previewitem',
            index=models.Index(fields=['preview', 'position'], name='preview_ite_preview_ded18d_idx'),
        ),
    ]
