# Generated by Django 6.0.3 on 2026-03-06 09:39

import creation_studio.models.core
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation_studio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandDNA',
            fields=[
                ('uuid', models.CharField(default=creation_studio.models.core.generate_uuid, editable=False, max_length=17, primary_key=True, serialize=False)),
                ('primary_color', models.CharField(blank=True, help_text='Hex color code', max_length=7)),
                ('secondary_color', models.CharField(blank=True, help_text='Hex color code', max_length=7)),
                ('accent_color', models.CharField(blank=True, help_text='Hex color code', max_length=7)),
                ('complementary_color', models.CharField(blank=True, help_text='Hex color code', max_length=7)),
                ('font_body_family', models.CharField(blank=True, max_length=100)),
                ('font_headings_family', models.CharField(blank=True, max_length=100)),
                ('voice_tone', models.CharField(blank=True, max_length=255)),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated brand keywords')),
                ('description', models.TextField(blank=True, help_text='Brand description and positioning')),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brand DNA',
                'verbose_name_plural': 'Brand DNA',
                'db_table': 'brand_dna',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('uuid', models.CharField(default=creation_studio.models.core.generate_uuid, editable=False, max_length=17, primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, help_text='Owner/user identifier', max_length=17, null=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('page_url', models.URLField(blank=True, max_length=500, validators=[django.core.validators.URLValidator()])),
                ('logo_url', models.URLField(blank=True, max_length=500, validators=[django.core.validators.URLValidator()])),
                ('is_active', models.BooleanField(default=True)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dna', models.OneToOneField(blank=True, db_column='dna_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand', to='creation_studio.branddna')),
            ],
            options={
                'db_table': 'brands',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Creation',
            fields=[
                ('uuid', models.CharField(default=creation_studio.models.core.generate_uuid, editable=False, max_length=17, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('post_type', models.CharField(choices=[('post', 'Post'), ('carousel', 'Carousel'), ('reel', 'Reel'), ('story', 'Story'), ('infographic', 'Infographic')], default='post', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('done', 'Done'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('platforms', models.CharField(blank=True, help_text='Comma-separated platforms (e.g., instagram, tiktok)', max_length=255)),
                ('post_tone', models.CharField(blank=True, help_text='Desired emotional impact', max_length=50)),
                ('original_prompt', models.TextField(blank=True)),
                ('research_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(db_column='brand_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='creations', to='creation_studio.brand')),
            ],
            options={
                'db_table': 'creations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('uuid', models.CharField(default=creation_studio.models.core.generate_uuid, editable=False, max_length=17, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('prompt', models.TextField(help_text='The optimized super-prompt used')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('generation_params', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creation', models.ForeignKey(db_column='creation_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='creation_studio.creation')),
                ('parent', models.ForeignKey(blank=True, db_column='parent_uuid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='creation_studio.generation')),
            ],
            options={
                'db_table': 'generations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('uuid', models.CharField(default=creation_studio.models.core.generate_uuid, editable=False, max_length=17, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=1000, validators=[django.core.validators.URLValidator()])),
                ('file_type', models.CharField(choices=[('image/jpeg', 'JPEG Image'), ('image/png', 'PNG Image'), ('image/webp', 'WebP Image'), ('video/mp4', 'MP4 Video')], max_length=30)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='Size in bytes', null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('storage_provider', models.CharField(blank=True, default='cloudinary', max_length=50)),
                ('storage_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generation', models.ForeignKey(db_column='generation_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='creation_studio.generation')),
            ],
            options={
                'db_table': 'media_files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformInsight',
            fields=[
                ('uuid', models.CharField(default=creation_studio.models.core.generate_uuid, editable=False, max_length=17, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('twitter', 'Twitter/X'), ('pinterest', 'Pinterest'), ('youtube', 'YouTube')], max_length=20)),
                ('date', models.DateField()),
                ('followers', models.PositiveIntegerField(default=0)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('reach', models.PositiveIntegerField(default=0)),
                ('engagement_rate', models.FloatField(default=0.0)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(db_column='brand_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='platform_insights', to='creation_studio.brand')),
            ],
            options={
                'db_table': 'platform_insights',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('uuid', models.CharField(default=creation_studio.models.core.generate_uuid, editable=False, max_length=17, primary_key=True, serialize=False)),
                ('copy', models.TextField(blank=True, help_text='Post caption/copy')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('post_type', models.CharField(choices=[('post', 'Post'), ('carousel', 'Carousel'), ('reel', 'Reel'), ('story', 'Story'), ('infographic', 'Infographic')], default='post', max_length=20)),
                ('platforms', models.CharField(blank=True, help_text='Comma-separated platforms', max_length=255)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('comments', models.PositiveIntegerField(default=0)),
                ('shares', models.PositiveIntegerField(default=0)),
                ('reach', models.PositiveIntegerField(default=0)),
                ('engagement_rate', models.FloatField(default=0.0)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(db_column='brand_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='creation_studio.brand')),
                ('creation', models.ForeignKey(blank=True, db_column='creation_uuid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='creation_studio.creation')),
            ],
            options={
                'db_table': 'posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['slug'], name='brands_slug_6a4b1c_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['is_active'], name='brands_is_acti_101dba_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['industry'], name='brands_industr_2b91ff_idx'),
        ),
        migrations.AddIndex(
            model_name='creation',
            index=models.Index(fields=['brand', 'status'], name='creations_brand_u_161e6a_idx'),
        ),
        migrations.AddIndex(
            model_name='creation',
            index=models.Index(fields=['status'], name='creations_status_484e73_idx'),
        ),
        migrations.AddIndex(
            model_name='creation',
            index=models.Index(fields=['created_at'], name='creations_created_6565e7_idx'),
        ),
        migrations.AddIndex(
            model_name='generation',
            index=models.Index(fields=['creation', 'status'], name='generations_creatio_6b2fbb_idx'),
        ),
        migrations.AddIndex(
            model_name='generation',
            index=models.Index(fields=['status'], name='generations_status_8c8b21_idx'),
        ),
        migrations.AddIndex(
            model_name='generation',
            index=models.Index(fields=['parent'], name='generations_parent__b8dc2b_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['generation'], name='media_files_generat_54889d_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['file_type'], name='media_files_file_ty_6d2622_idx'),
        ),
        migrations.AddIndex(
            model_name='platforminsight',
            index=models.Index(fields=['brand', 'platform'], name='platform_in_brand_u_22e758_idx'),
        ),
        migrations.AddIndex(
            model_name='platforminsight',
            index=models.Index(fields=['date'], name='platform_in_date_995954_idx'),
        ),
        migrations.AddIndex(
            model_name='platforminsight',
            index=models.Index(fields=['platform'], name='platform_in_platfor_fae47e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='platforminsight',
            unique_together={('brand', 'platform', 'date')},
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['brand', 'status'], name='posts_brand_u_717d0e_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status'], name='posts_status_bd5975_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['scheduled_date'], name='posts_schedul_ec49e2_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['created_at'], name='posts_created_060265_idx'),
        ),
    ]
