# Generated by Django 6.0.3 on 2026-03-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation_studio', '0002_branddna_brand_creation_generation_mediafile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='tenant_id',
            field=models.CharField(blank=True, db_index=True, help_text='SIA Tenant UUID - which organization this brand belongs to', max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='creation',
            name='user_id',
            field=models.CharField(blank=True, db_index=True, help_text='SIA User UUID who created this project', max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='user_id',
            field=models.CharField(blank=True, db_index=True, help_text='SIA User UUID who owns this post', max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='user_id',
            field=models.CharField(blank=True, db_index=True, help_text='SIA User UUID (from OAuth/JWT) - who owns this brand', max_length=36, null=True),
        ),
    ]
