# Generated by Django 6.0.3 on 2026-03-11 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation_studio', '0002_branddna_preview_brand_creation_generation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='tenant_id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='platforms',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user_id',
        ),
        migrations.AddField(
            model_name='brand',
            name='primary_color',
            field=models.CharField(blank=True, help_text='Hex color code', max_length=7),
        ),
        migrations.AddField(
            model_name='generation',
            name='keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='preview',
            field=models.ForeignKey(blank=True, db_column='preview_uuid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='creation_studio.preview'),
        ),
        migrations.AlterField(
            model_name='previewitem',
            name='generation',
            field=models.ForeignKey(db_column='generation_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='preview_items', to='creation_studio.generation'),
        ),
    ]
