# Generated by Django 6.0.3 on 2026-03-11 13:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation_studio', '0003_align_schema_v3'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(help_text='Public URL of the asset (e.g. Cloudinary)', max_length=1000)),
                ('file_type', models.CharField(blank=True, help_text='MIME type (e.g. image/jpeg, video/mp4)', max_length=100)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='Size in bytes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generation', models.ForeignKey(db_column='generation_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='creation_studio.generation')),
            ],
            options={
                'verbose_name': 'Media File',
                'verbose_name_plural': 'Media Files',
                'db_table': 'media_files',
                'ordering': ['created_at'],
            },
        ),
    ]
