# Generated by Django 6.0.3 on 2026-03-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation_studio', '0004_mediafile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creation',
            name='post_type',
            field=models.CharField(choices=[('post', 'Post'), ('carousel', 'Carousel'), ('reel', 'Reel'), ('video', 'Video'), ('story', 'Story'), ('infographic', 'Infographic')], default='post', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('post', 'Post'), ('carousel', 'Carousel'), ('reel', 'Reel'), ('video', 'Video'), ('story', 'Story'), ('infographic', 'Infographic')], default='post', max_length=20),
        ),
    ]
