# Generated by Django 6.0.3 on 2026-03-10 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation_studio', '0004_alter_brand_uuid_alter_branddna_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creation',
            name='brand',
            field=models.ForeignKey(blank=True, db_column='brand_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creations', to='creation_studio.brand'),
        ),
    ]
