# Generated by Django 6.0.3 on 2026-03-16 16:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand_dna_extractor', '0001_initial'),
        ('creation_studio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformInsight',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('twitter', 'Twitter/X'), ('pinterest', 'Pinterest'), ('youtube', 'YouTube')], max_length=20)),
                ('date', models.DateField()),
                ('followers', models.PositiveIntegerField(default=0)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('reach', models.PositiveIntegerField(default=0)),
                ('engagement_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(db_column='brand_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='platform_insights', to='brand_dna_extractor.brand')),
            ],
            options={
                'db_table': 'platform_insights',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['brand', 'platform'], name='platform_in_brand_u_22e758_idx'), models.Index(fields=['date'], name='platform_in_date_995954_idx'), models.Index(fields=['platform'], name='platform_in_platfor_fae47e_idx')],
                'unique_together': {('brand', 'platform', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, db_index=True, help_text='SIA User UUID', max_length=36, null=True)),
                ('final_copy', models.TextField(blank=True, help_text='Final post caption/copy')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('post_type', models.CharField(choices=[('post', 'Post'), ('image', 'Image'), ('copy', 'Copy'), ('carousel', 'Carousel'), ('reel', 'Reel'), ('video', 'Video'), ('story', 'Story'), ('infographic', 'Infographic')], default='post', max_length=20)),
                ('platforms', models.CharField(blank=True, help_text='Comma-separated platforms', max_length=255)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('comments', models.PositiveIntegerField(default=0)),
                ('shares', models.PositiveIntegerField(default=0)),
                ('reach', models.PositiveIntegerField(default=0)),
                ('engagement_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(db_column='brand_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='brand_dna_extractor.brand')),
                ('preview', models.ForeignKey(blank=True, db_column='preview_uuid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='creation_studio.preview')),
            ],
            options={
                'db_table': 'posts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['brand', 'status'], name='posts_brand_u_717d0e_idx'), models.Index(fields=['status'], name='posts_status_bd5975_idx'), models.Index(fields=['scheduled_date'], name='posts_schedul_ec49e2_idx'), models.Index(fields=['created_at'], name='posts_created_060265_idx')],
            },
        ),
    ]
